from enum import Enum, auto


class OpCode(Enum):
    LOAD_CONST = auto()
    LOAD_LOCAL = auto()
    STORE_LOCAL = auto()
    LOAD_NAME = auto()
    STORE_NAME = auto()
    LOAD_UPVALUE = auto()
    STORE_UPVALUE = auto()
    BINARY_ADD = auto()
    BINARY_SUB = auto()
    BINARY_MUL = auto()
    BINARY_DIV = auto()
    BINARY_MOD = auto()
    BINARY_POW = auto()
    BINARY_FLOOR_DIV = auto()
    COMPARE_EQ = auto()
    COMPARE_NE = auto()
    COMPARE_LT = auto()
    COMPARE_LE = auto()
    COMPARE_GT = auto()
    COMPARE_GE = auto()
    JUMP = auto()
    JUMP_IF_FALSE = auto()
    POP_JUMP_IF_FALSE = auto()
    LOOP = auto()
    CALL_FUNCTION = auto()
    RETURN_VALUE = auto()
    MAKE_CLOSURE = auto()
    BUILD_LIST = auto()
    BUILD_DICT = auto()
    BUILD_SET = auto()
    BUILD_TUPLE = auto()
    LOAD_ATTR = auto()
    STORE_ATTR = auto()
    LOAD_INDEX = auto()
    STORE_INDEX = auto()
    GET_ITERATOR = auto()
    FOR_ITER = auto()
    POP_TOP = auto()
    DUP_TOP = auto()
    UNARY_NEGATIVE = auto()
    UNARY_NOT = auto()
    LOGICAL_AND = auto()
    LOGICAL_OR = auto()